### ISSUE TITLE
Hello, how to download the singularity image/recipe of SnapHiC using docker？

### ISSUE THREAD

**Issue by YusenYe** [HuMingLab/SnapHiC#2]
Hello，excuse me. I can't search for snapHiC from https://hub.docker.com. Can you tell me how to use snapHiC on docker. Thanks very much!

**Comment by armensly** [comment]
We don't have a docker container for SnapHiC, we have a singularity container that can be downloaded from [here](renlab.sdsc.edu/abnousa/snapHiC/singularity_releases/).
