### ISSUE TITLE
Help about cluster and cell-type annoation results in your paper

### ISSUE THREAD

**Issue by YusenYe** [HuMingLab/SnapHiC#3]
Hi，I am YusenYe，a researcher about 3D genome analysis.  I am doing a project about single cell using scm3C-seq data of brain tissue following your paper "SnapHiC: a computational pipeline to map chromatin contacts from single cell Hi-C data".
However, I can't download cluster and cell-type identification results of Fig2a (https://www.biorxiv.org/content/10.1101/2020.12.13.422543v1.full)  in your paper. The annotated results are very important to my project. Can you send me clusters and cell-type identification results, which annotated the cell-type of each cell? Thanks very much. my email address is ccyeyusen@sina.com.

Regards，
Yusen

**Comment by HuMingLab** [comment]
I just emailed you the cell type information for each cell. Please feel free to contact us if you have any additional questions.

**Comment by YusenYe** [comment]
Thanks very much, it's very useful for my project.
