### ISSUE TITLE
Space issues

### ISSUE THREAD

**Issue by terencewtli** [HuMingLab/SnapHiC#4]
Hi,

Thank you for providing this tool! I have a single-cell dataset with ~34,000 cells, do you have any recommendations for conserving space? I want to generate the loops at 10kb resolution. I was thinking of compressing the output of the `rwr` `.bedpe` files, but was wondering if you had any better suggestions.

**Comment by HuMingLab** [comment]
Hi, thank you for your interest in our SnapHiC tool. For your ~34,000 cells, are they from the same cell type, and what is the sequencing depth of each cell? In our previous experience, we only applied SnapHiC to cells belonging to the same cell type, and with sufficiently high sequencing depth (>150,000 contacts per cell). For a large number of cells, rwr and .bedpe files may take lots of space. You may compress these files into the hdf5 format.
