### ISSUE TITLE
outlier_count meaning

### ISSUE THREAD

**Issue by zhang-jiankun** [HuMingLab/SnapHiC#5]
Hi,

Thanks for the detailed documents. I was wondering if the outlier_count column means the number of cells with certain chromatin loops.

Best,
Jiankun

**Comment by HuMingLab** [comment]
Hi Jiankun, 

For each chromatin loop, we reported the # of cells with extremely large Z-score (Z-score>1.96). It can reflect the contact strength of each loop. You can find more details in our SnapHiC paper method section (Visualization of scHi-C and sn-m3C-seq data using percentage (%) of outlier cells matrix).

Best,
Ming
