### ISSUE TITLE
normalize_imputed_matrices.py running time

### ISSUE THREAD

**Issue by AmyTanJ** [HuMingLab/SnapHiC#8]
I have tried to run `normalize_along_diagonal_from_numpy()`  function in `normalize_imputed_matrices.py` for chromosome Hic matrix of each cell in 10kb, but it takes too long to finish the normalization loop.
How can I reduce the running time effectively?

**Comment by HuMingLab** [comment]
You may use a larger number of CPUs to speed up the computing time. You may also try our recent work SnapHiC2: https://pubmed.ncbi.nlm.nih.gov/35685374/.

**Comment by AmyTanJ** [comment]
您好，我是谭佳慧，您的邮件我已经收到，我会尽快回复，祝您万事如意，家庭幸福！
